#!/bin/usr/env python

import math
import os
import random
import re
import sys

# Complete the beautifulDays function below.
def beautifulDays(i, j, k):
    l=[]
    for n in range(i, j+1):
        
        x=n
        rev=0
        s=0
        while n!=0:
            rem = n%10
            rev = rev*10+rem
            n=int(n/10)
        s=abs(rev-x)
        if s%k==0:
            l.append(n)
        else:
            continue    
    return  len(l)


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ijk = input().split()

    i = int(ijk[0])

    j = int(ijk[1])

    k = int(ijk[2])

    result = beautifulDays(i, j, k)

    fptr.write(str(result) + '\n')

    fptr.close()
