#!/bin/usr/env python

import math
import os
import random
import re
import sys

# Complete the designerPdfViewer function below.
def designerPdfViewer(h, word):

    temp=0
    y = len(word)
    for i in range(y):
        ascii = ord(word[i])
        x = h[ascii - 97]
        if x>temp:
            temp=x

    return  temp*y


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    h = list(map(int, input().rstrip().split()))

    word = input()

    result = designerPdfViewer(h, word)

    fptr.write(str(result) + '\n')

    fptr.close()
