#!/bin/usr/env python

import math
import os
import random
import re
import sys

# Complete the equalizeArray function below.
def equalizeArray(arr):
    n=[]
    total=0
    s = set(arr)
    l = list(s)
    for i in range(len(l)):
        p=arr.count(l[i])
        total=total+p
        n.append(p)

    q=max(n)
    return total-q    


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = equalizeArray(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
