#!/bin/usr/env python

import math
import os
import random
import re
import sys

# Complete the minimumDistances function below.
def minimumDistances(a):
    l=[]
    m=[]
    for i in range(0, n-1):
        d=0
        for j in range(i+1, n):
            if a[i]==a[j]:
                d = abs(i-j)
                l.append(d)
                continue
                
            else:
                continue
        if l==[]:
            continue
        else:

            m.append(min(l))

    if m==[]:
        return -1
    else:    
        return min(m)    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    a = list(map(int, input().rstrip().split()))

    result = minimumDistances(a)

    fptr.write(str(result) + '\n')

    fptr.close()
