#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    # Write your code here
    m = []
    for i in range(len(a)):
        countA = 1
        countB = 1
        for j in range(i+1, len(a)):

            if 1+a[i] == a[j]:
                
                countA = countA + 1
            elif a[i] == a[j] + 1:
                
                countB = countB + 1
            elif a[i] == a[j]:

                countA = countA+1
                countB = countB+1
            else:
                continue
        m.append(countA)
        m.append(countB)

    return max(m)                


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
