#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the serviceLane function below.
def serviceLane(n, cases, width):
    # print(cases)
    # print(width)
    m=[]
    
    l = len(cases)
    #print(l)
    for i in range(l):
        lower = cases[i][0]
        upper = cases[i][1]

        y = width[lower:(upper+1)]
        #print(y)
        m.append(min(y))
        #print(m)
    
    return m    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nt = input().split()

    n = int(nt[0])

    t = int(nt[1])

    width = list(map(int, input().rstrip().split()))

    cases = []

    for _ in range(t):
        cases.append(list(map(int, input().rstrip().split())))

    result = serviceLane(n, cases, width)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
